modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL = "https://github.com/KekeCreations/Arts-and-Crafts-Compatibility/issues"
updateJSONURL="https://raw.githubusercontent.com/KekeCreations/Arts-and-Crafts-Compatibility/1.20.1x/forge_updates.json"
[[mods]] #mandatory
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://kekecreations.boomla.net/minecraft/java-mods/arts-and-crafts"
logoFile = "${mod_id}.png"
authors = "KekeCreations and Arbeet!"
description = '''${description}'''




[[dependencies.${mod_id}]]
modId="arts_and_crafts"
mandatory=true
versionRange="[1.1.7,)"
ordering="AFTER"
side="BOTH"
#SOFT DEPENDENCIES
[[dependencies.${mod_id}]]
modId="ecologics"
mandatory=false
versionRange="[2.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
